all:
  hosts:
    local:
      ansible_host: localhost
    raspi:
      ansible_host: localhost
      ansible_port: 2222
      ansible_ssh_user: admin
      ansible_ssh_pass: raspiblitz
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
